name: slider_view_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  flutter:
    sdk: flutter

  slider_view:
    path: ../

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
